### ISSUE TITLE
Doesn't seems to work with Unity 2020.3

### ISSUE THREAD

**Issue by RomainBitard** [louthy/language-ext#992]
Hello, did anyone test this lib with Unity 2020.3 ? 
I imported the dll extracted from the nuget package into my asset folder but there are compilation errors and missing references. 
Is it my way of importing the dll or it's not working with unity ?

**Comment by RomainBitard** [comment]
Assembly 'Assets/LanguageExt.Core.dll' will not be loaded due to errors:
Unable to resolve reference 'System.Threading.Tasks.Extensions'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
Unable to resolve reference 'System.Buffers'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
Unable to resolve reference 'System.Memory'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.
Unable to resolve reference 'Microsoft.Bcl.AsyncInterfaces'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.

**Comment by louthy** [comment]
Does anyone have any insight here?  I'm not a Unity user, so I'm not sure what it does and doesn't support.

**Comment by RomainBitard** [comment]
I'm neither a unity user or C# user so I might be doing something wrong, unzipping the nuget package is ok from a C# point of view ?

**Comment by RomainBitard** [comment]
I managed to make Language-ext work (didn't test everything obviously but the few features I tested worked really great on windows/android. 
Here are my steps to make it work even in unit testing : 

- Download 4.0.3 

- Extract folder pjv into a folder of your choice (I named mine LanguageExt) in unity Asset folder (except Newtonsoft.json.dll because unity already has one (on 2020.3 LTS).

To make it work in unit tests : 

- In your test assembly definition tick override references and import all the dlls
![image](https://user-images.githubusercontent.com/13960970/160152720-0935eab9-8538-458e-8210-6c82c867aeb5.png)
